# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Lockfile generation for reproducible benchmark runs.

The lockfile is the original recipe YAML with a `lock:` section appended.
It captures everything needed to understand and reproduce a run:

- The recipe (unchanged, with aliases and identity block)
- lock.slurm: where and how the job ran (job ID, cluster, nodes)
- lock.resolved: what aliases mapped to (local paths)
- lock.verification: identity checks (did runtime match declarations?)
- lock.fingerprints: per-worker runtime environment (GPU, frameworks, packages)
- lock.results: benchmark metrics (throughput, latency)
- lock.hashes: exact recipe, portable intent, and site binding hashes
- lock.artifacts: observed artifact metadata and relative file manifests

The lockfile IS a valid recipe — `srtctl apply -f reproduce/recipe.lock.yaml` works.
When applying a lockfile, srtctl compares the new run against lock.fingerprints.

All operations are fault-tolerant — lockfile writing never blocks or fails a job.
"""

from __future__ import annotations

import contextlib
import getpass
import hashlib
import json
import logging
import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

import yaml

from srtctl.core.fingerprint import load_fingerprint

if TYPE_CHECKING:
    from srtctl.core.schema import SrtConfig

logger = logging.getLogger(__name__)

# Lockfile format version — bump when the structure changes
_LOCKFILE_VERSION = 2
_MAX_INLINE_HASH_BYTES = 64 * 1024 * 1024
_MAX_MANIFEST_FILES = 20_000
_MAX_MANIFEST_HASH_BYTES = 256 * 1024 * 1024
_REPRODUCE_DIR = "reproduce"
_FINGERPRINTS_DIR = "fingerprints"
_LOCKFILE_NAME = "recipe.lock.yaml"
_REPRODUCTION_REPORT_NAME = "reproduction-report.txt"


def reproduce_dir(output_dir: Path) -> Path:
    """Directory for reproducibility artifacts within a run output."""
    return output_dir / _REPRODUCE_DIR


def lockfile_path(output_dir: Path) -> Path:
    """Canonical lockfile path for a run output directory."""
    return reproduce_dir(output_dir) / _LOCKFILE_NAME


def fingerprints_dir(output_dir: Path) -> Path:
    """Directory for raw per-worker fingerprint JSON files."""
    return reproduce_dir(output_dir) / _FINGERPRINTS_DIR


def reproduction_report_path(output_dir: Path) -> Path:
    """Canonical reproduction report path for a run output directory."""
    return reproduce_dir(output_dir) / _REPRODUCTION_REPORT_NAME


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _hash_record(value: str, *, status: str = "complete", **extra: Any) -> dict[str, Any]:
    record = {
        "algorithm": "sha256",
        "status": status,
    }
    if status in {"complete", "partial"}:
        record["value"] = hashlib.sha256(value.encode()).hexdigest()
    record.update({k: v for k, v in extra.items() if v not in (None, {}, [], ())})
    return record


def _hash_data(data: Any, *, status: str = "complete", **extra: Any) -> dict[str, Any]:
    canonical = json.dumps(data, sort_keys=True, separators=(",", ":"), default=str)
    return _hash_record(canonical, status=status, **extra)


def _file_hash_record(path: Path, *, max_bytes: int = _MAX_INLINE_HASH_BYTES) -> dict[str, Any]:
    """Hash a regular file when cheap enough, always returning an explicit status."""
    try:
        resolved = path.resolve()
        if not resolved.exists():
            return _hash_record("", status="error", error=f"not found: {path}")
        if resolved.is_dir():
            return _hash_record("", status="skipped_directory")
        if not resolved.is_file():
            return _hash_record("", status="error", error=f"not a regular file: {path}")

        size = resolved.stat().st_size
        if size > max_bytes:
            return _hash_record(
                "",
                status="skipped_large_file",
                size_bytes=size,
                max_inline_bytes=max_bytes,
            )
        return {
            "algorithm": "sha256",
            "status": "complete",
            "value": _sha256_file(resolved),
            "size_bytes": size,
        }
    except Exception as e:
        return _hash_record("", status="error", error=str(e))


def _hash_text(text: str) -> dict[str, Any]:
    return _hash_record(text, status="complete", size_bytes=len(text.encode()))


# Comment inserted above the lock section
_LOCK_COMMENT = """\

# ============================================================================
# Lock section — generated by srtctl after a run. DO NOT edit manually.
#
# This records exactly what happened when this recipe was executed.
# To reproduce on another cluster:
#   1. Update the recipe's site: paths for that cluster, if needed
#   2. Run: srtctl apply -f reproduce/recipe.lock.yaml
#   3. srtctl will compare your runtime against the original fingerprints
#
# The recipe above is unchanged from what the author wrote.
# ============================================================================
"""

# SLURM environment variables to capture.
_SLURM_ENV_KEYS = [
    ("job_id", "SLURM_JOB_ID"),
    ("job_name", "SLURM_JOB_NAME"),
    ("cluster", "SLURM_CLUSTER_NAME"),
    ("account", "SLURM_JOB_ACCOUNT"),
    ("partition", "SLURM_JOB_PARTITION"),
    ("nodelist", "SLURM_JOB_NODELIST"),
    ("num_nodes", "SLURM_JOB_NUM_NODES"),
    ("gpus_per_node", "SLURM_GPUS_PER_NODE"),
    ("time_limit", "SLURM_TIMELIMIT"),
]


def collect_slurm_context() -> dict[str, Any]:
    """Collect SLURM job context from environment variables."""
    ctx: dict[str, Any] = {}

    for key, env_var in _SLURM_ENV_KEYS:
        val = os.environ.get(env_var)
        if val is not None:
            ctx[key] = val

    with contextlib.suppress(Exception):
        ctx["user"] = getpass.getuser()

    ctx["cwd"] = str(Path.cwd())

    srtctl_root = os.environ.get("SRTCTL_ROOT")
    if srtctl_root:
        ctx["srtctl_root"] = srtctl_root

    try:
        import subprocess

        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=2,
            cwd=srtctl_root or None,
        )
        if result.returncode == 0:
            ctx["srtctl_commit"] = result.stdout.strip()
    except Exception:
        pass

    return ctx


def collect_worker_fingerprints(log_dir: Path) -> dict[str, Any] | None:
    """Load per-worker fingerprint files into a dict keyed by worker name."""
    try:
        fp_files = sorted(log_dir.glob("fingerprint_*.json"))
    except Exception as e:
        logger.debug("Failed to glob fingerprint files in %s: %s", log_dir, e)
        return None

    if not fp_files:
        return None

    result: dict[str, Any] = {}
    for fp_file in fp_files:
        fp = load_fingerprint(fp_file)
        if fp is not None:
            worker_key = fp_file.stem.removeprefix("fingerprint_")
            result[worker_key] = fp

    return result if result else None


def _compact_dict(data: dict[str, Any]) -> dict[str, Any]:
    """Drop None/empty values for readable lockfile sections."""
    return {k: v for k, v in data.items() if v not in (None, {}, [], ())}


def _path_metadata(path_str: str | None, *, hash_files: bool = True) -> dict[str, Any]:
    """Cheap, non-blocking path manifest used for lockfile artifacts."""
    if not path_str:
        return {}
    expanded = os.path.expandvars(path_str)
    if expanded.startswith("hf:"):
        return {"path": expanded, "kind": "huggingface_id", "exists": None}

    path = Path(expanded)
    try:
        resolved = path.resolve()
        meta: dict[str, Any] = {"path": str(resolved), "exists": resolved.exists()}
        if not resolved.exists():
            return meta
        stat = resolved.stat()
        meta["mtime_ns"] = stat.st_mtime_ns
        if resolved.is_dir():
            meta["kind"] = "directory"
            if hash_files:
                meta["hash"] = _hash_record("", status="skipped_directory")
        elif resolved.is_file():
            meta["kind"] = "file"
            meta["size_bytes"] = stat.st_size
            if hash_files:
                meta["hash"] = _file_hash_record(resolved)
        else:
            meta["kind"] = "other"
        return meta
    except Exception as e:
        return {"path": expanded, "exists": "unknown", "error": str(e)}


def _iter_files_deterministic(root: Path):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for filename in sorted(filenames):
            path = Path(dirpath) / filename
            if path.is_file():
                yield path


def _relative_file_manifest(path_str: str | None) -> dict[str, Any]:
    """Build a path-independent manifest for a file tree.

    The manifest hash deliberately excludes the absolute root path. Large files
    are listed by relative path and size, but not content-hashed by default.
    """
    if not path_str:
        return {"hash": _hash_record("", status="error", error="missing path")}
    expanded = os.path.expandvars(path_str)
    if expanded.startswith("hf:"):
        return {
            "kind": "huggingface_id",
            "hash": _hash_record("", status="skipped_directory", reason="remote HuggingFace ID"),
        }

    root = Path(expanded)
    try:
        resolved = root.resolve()
        if not resolved.exists():
            return {"hash": _hash_record("", status="error", error=f"not found: {expanded}")}

        if resolved.is_file():
            files = iter([resolved])
            base = resolved.parent
            kind = "file"
        elif resolved.is_dir():
            files = _iter_files_deterministic(resolved)
            base = resolved
            kind = "directory"
        else:
            return {"hash": _hash_record("", status="error", error=f"unsupported path kind: {expanded}")}

        entries: list[dict[str, Any]] = []
        total_files_seen = 0
        total_bytes = 0
        hashed_bytes = 0
        partial = False
        truncated = False

        for file_path in files:
            total_files_seen += 1
            if len(entries) >= _MAX_MANIFEST_FILES:
                partial = True
                truncated = True
                break

            stat = file_path.stat()
            rel_path = file_path.relative_to(base).as_posix()
            total_bytes += stat.st_size
            entry: dict[str, Any] = {
                "path": rel_path,
                "size_bytes": stat.st_size,
            }

            if stat.st_size > _MAX_INLINE_HASH_BYTES:
                entry["hash"] = _hash_record(
                    "",
                    status="skipped_large_file",
                    size_bytes=stat.st_size,
                    max_inline_bytes=_MAX_INLINE_HASH_BYTES,
                )
                partial = True
            elif hashed_bytes + stat.st_size > _MAX_MANIFEST_HASH_BYTES:
                entry["hash"] = _hash_record(
                    "",
                    status="partial",
                    reason="manifest hash byte budget exceeded",
                    max_manifest_hash_bytes=_MAX_MANIFEST_HASH_BYTES,
                )
                partial = True
            else:
                file_hash = _file_hash_record(file_path)
                file_hash.pop("size_bytes", None)
                entry["hash"] = file_hash
                if entry["hash"].get("status") != "complete":
                    partial = True
                hashed_bytes += stat.st_size

            entries.append(entry)

        payload = {
            "kind": kind,
            "entries": entries,
            "truncated": truncated,
        }
        status = "partial" if partial else "complete"
        return {
            "kind": kind,
            "file_count": len(entries),
            "total_files_seen": total_files_seen,
            "total_bytes": total_bytes,
            "entries": entries,
            "hash": _hash_data(
                payload,
                status=status,
                file_count=len(entries),
                total_files_seen=total_files_seen,
                total_bytes=total_bytes,
                truncated=truncated,
            ),
        }
    except Exception as e:
        return {"hash": _hash_record("", status="error", error=str(e))}


def _infer_hf_metadata(path_str: str | None) -> dict[str, Any]:
    """Infer HuggingFace identity from common local download metadata files."""
    if not path_str or path_str.startswith("hf:"):
        return {"hf_repo": path_str[3:]} if path_str and path_str.startswith("hf:") else {}

    path = Path(os.path.expandvars(path_str))
    if not path.exists() or not path.is_dir():
        return {}

    info: dict[str, Any] = {}
    for refs_path in [path / ".huggingface" / "refs" / "main", path / "refs" / "main"]:
        with contextlib.suppress(Exception):
            if refs_path.exists():
                info["revision"] = refs_path.read_text().strip()
                break

    if "revision" not in info:
        cache_dl = path / ".cache" / "huggingface" / "download"
        if cache_dl.is_dir():
            for meta_file in sorted(cache_dl.glob("*.metadata")):
                with contextlib.suppress(Exception):
                    first_line = meta_file.read_text().splitlines()[0].strip()
                    if len(first_line) == 40 and all(c in "0123456789abcdef" for c in first_line):
                        info["revision"] = first_line
                        break

    meta_json = path / ".huggingface" / "download_metadata.json"
    with contextlib.suppress(Exception):
        if meta_json.exists():
            metadata = json.loads(meta_json.read_text())
            if metadata.get("repo_id"):
                info["hf_repo"] = metadata["repo_id"]
            if metadata.get("commit_hash"):
                info["revision"] = metadata["commit_hash"]

    config_json = path / "config.json"
    with contextlib.suppress(Exception):
        if config_json.exists():
            config_data = json.loads(config_json.read_text())
            if config_data.get("_name_or_path"):
                info.setdefault("model_id", config_data["_name_or_path"])

    return info


def _first_worker_frameworks(worker_fingerprints: dict[str, Any] | None) -> dict[str, str]:
    if not worker_fingerprints:
        return {}
    for fingerprint in worker_fingerprints.values():
        frameworks = fingerprint.get("frameworks")
        if isinstance(frameworks, dict):
            return frameworks
    return {}


def _frameworks_by_worker(worker_fingerprints: dict[str, Any] | None) -> dict[str, Any]:
    if not worker_fingerprints:
        return {}
    result = {}
    for worker, fingerprint in worker_fingerprints.items():
        frameworks = fingerprint.get("frameworks")
        if isinstance(frameworks, dict):
            result[worker] = frameworks
    return result


def _strip_empty(value: Any) -> Any:
    if isinstance(value, dict):
        return {k: cleaned for k, v in value.items() if (cleaned := _strip_empty(v)) not in (None, {}, [], ())}
    if isinstance(value, list):
        return [cleaned for v in value if (cleaned := _strip_empty(v)) not in (None, {}, [], ())]
    if isinstance(value, tuple):
        return [_strip_empty(v) for v in value]
    return value


def _mount_target(mount_spec: str) -> str:
    return mount_spec.split(":", 1)[1] if ":" in mount_spec else mount_spec


def _normalized_intent_payload(config: SrtConfig) -> dict[str, Any]:
    """Hashable config intent with cluster-local site bindings removed."""
    from srtctl.core.schema import SrtConfig

    data = SrtConfig.Schema().dump(config)
    data.pop("lock", None)
    data.pop("slurm", None)
    data.pop("output", None)

    site = data.get("site")
    if isinstance(site, dict):
        site_intent: dict[str, Any] = {}
        model = site.get("model") or {}
        if model:
            site_intent["model"] = {k: model.get(k) for k in ("hf_repo", "revision", "precision")}

        spec = site.get("speculative_model") or {}
        if spec:
            site_intent["speculative_model"] = {k: spec.get(k) for k in ("target", "hf_repo", "revision")}

        container = site.get("container") or {}
        if container:
            site_intent["container"] = {k: container.get(k) for k in ("image", "digest", "frameworks")}

        mounts = site.get("mounts") or []
        if mounts:
            site_intent["mount_targets"] = sorted(_mount_target(mount_spec) for mount_spec in mounts)

        data["site"] = site_intent
        # model is synthesized from site.model.path/site.container.path for
        # internal compatibility, so it is deliberately excluded from intent.
        data.pop("model", None)
        # identity is also synthesized from site metadata; keeping it would make
        # the intent hash depend on compatibility plumbing.
        data.pop("identity", None)

        extra_mount = data.pop("extra_mount", None)
        if extra_mount:
            data["extra_mount_targets"] = sorted(_mount_target(mount_spec) for mount_spec in extra_mount)

        container_mounts = data.pop("container_mounts", None)
        if container_mounts:
            data["container_mount_targets"] = sorted(str(target) for target in container_mounts.values())

    return _strip_empty(data)


def _site_binding_payload(config: SrtConfig) -> dict[str, Any]:
    """Hashable cluster-local site binding payload."""
    if not config.site:
        return {}

    site = config.site
    binding: dict[str, Any] = {
        "name": site.name,
        "slurm": {
            "account": site.slurm.account,
            "partition": site.slurm.partition,
            "time_limit": site.slurm.time_limit,
            "network_interface": site.slurm.network_interface,
            "use_gpus_per_node_directive": site.slurm.use_gpus_per_node_directive,
            "use_segment_sbatch_directive": site.slurm.use_segment_sbatch_directive,
            "use_exclusive_sbatch_directive": site.slurm.use_exclusive_sbatch_directive,
        },
        "output": {"path": site.output.path},
        "model": {"path": site.model.path if site.model else None},
        "container": {"path": site.container.path if site.container else None},
        "mounts": list(site.mounts or ()),
    }
    if site.speculative_model:
        binding["speculative_model"] = {
            "path": site.speculative_model.path,
            "target": site.speculative_model.target,
        }
    if config.extra_mount:
        binding["extra_mount"] = list(config.extra_mount)
    if config.container_mounts:
        binding["container_mounts"] = {str(host): str(target) for host, target in config.container_mounts.items()}
    return _strip_empty(binding)


def _hashes_section(config: SrtConfig, recipe_text: str | None) -> dict[str, Any]:
    hashes: dict[str, Any] = {
        "normalized_intent": _hash_data(
            _normalized_intent_payload(config),
            status="complete",
            payload_version=1,
        )
    }
    if recipe_text is not None:
        hashes["recipe_exact"] = _hash_text(recipe_text)
    if config.site:
        hashes["site_binding"] = _hash_data(
            _site_binding_payload(config),
            status="complete",
            payload_version=1,
        )
    return hashes


def _run_git(source_dir: Path, *args: str, timeout: int = 5) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(source_dir), *args],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        return None
    return None


def _source_root() -> Path:
    env_source = os.environ.get("SRTCTL_SOURCE_DIR")
    if env_source:
        return Path(env_source)
    return Path(__file__).resolve().parents[3]


def _git_state(source_dir: Path) -> dict[str, Any]:
    commit = _run_git(source_dir, "rev-parse", "HEAD")
    if not commit:
        return {"source_dir": str(source_dir), "hash": _hash_record("", status="error", error="not a git checkout")}

    status = _run_git(source_dir, "status", "--porcelain=v1", "--untracked-files=normal") or ""
    dirty = bool(status)
    diff = _run_git(source_dir, "diff", "--binary", "HEAD", "--", ".", timeout=10)
    if diff is None:
        dirty_hash = _hash_record("", status="error", error="git diff failed")
    else:
        dirty_hash = _hash_text(status + "\n" + diff)
        if dirty:
            dirty_hash["status"] = "partial"
            dirty_hash["coverage"] = "tracked diff plus untracked file names"

    return {
        "source_dir": str(source_dir),
        "commit": commit,
        "dirty": dirty,
        "dirty_tree_hash": dirty_hash,
    }


def _runtime_file_record(path: Path, root: Path | None = None) -> dict[str, Any]:
    record: dict[str, Any] = {"path": str(path)}
    if root:
        with contextlib.suppress(Exception):
            record["relative_path"] = path.relative_to(root).as_posix()
    record["hash"] = _file_hash_record(path)
    return record


def _find_setup_script(name: str) -> Path | None:
    candidates = [
        _source_root() / "configs" / name,
        Path(__file__).resolve().parents[3] / "configs" / name,
        Path("/configs") / name,
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def _runtime_code_artifacts(config: SrtConfig, output_dir: Path | None, log_dir: Path | None) -> dict[str, Any]:
    source_dir = _source_root()
    runtime: dict[str, Any] = {
        "srtctl": _git_state(source_dir),
    }

    files: dict[str, Any] = {}
    if output_dir:
        files["submitted_config"] = _runtime_file_record(output_dir / "config.yaml", output_dir)
        files["sbatch_script"] = _runtime_file_record(output_dir / "sbatch_script.sh", output_dir)
        runtime_configs = [
            _runtime_file_record(path, output_dir)
            for path in sorted(output_dir.glob("config_*.yaml"))
            if path.name != "config.yaml"
        ]
        if runtime_configs:
            files["runtime_configs"] = runtime_configs

    if log_dir:
        generated_configs = [_runtime_file_record(path, log_dir) for path in sorted(log_dir.glob("*.yaml"))]
        if generated_configs:
            files["generated_runtime_configs"] = generated_configs

    if config.setup_script:
        setup_path = _find_setup_script(config.setup_script)
        if setup_path:
            files["setup_script"] = {
                "name": config.setup_script,
                **_runtime_file_record(setup_path),
            }
        else:
            files["setup_script"] = {
                "name": config.setup_script,
                "hash": _hash_record("", status="error", error="setup script not found"),
            }

    if files:
        runtime["files"] = files
    return runtime


def _mount_manifest(mount_spec: str) -> dict[str, Any]:
    if ":" not in mount_spec:
        return {"spec": mount_spec, "error": "expected host:container"}
    source, target = mount_spec.split(":", 1)
    return {
        "source": source,
        "target": target,
        "observed": _path_metadata(source),
        "manifest": _relative_file_manifest(source),
    }


def build_artifacts_section(
    config: SrtConfig,
    worker_fingerprints: dict[str, Any] | None,
    resolved_log_dir: Path | None = None,
    output_dir: Path | None = None,
) -> dict[str, Any]:
    """Build declared/observed artifact metadata for reproducibility."""
    site = config.site
    artifacts: dict[str, Any] = {}

    if site and site.model:
        declared = _compact_dict(
            {
                "path": site.model.path,
                "hf_repo": site.model.hf_repo,
                "revision": site.model.revision,
                "precision": site.model.precision,
            }
        )
        artifacts["model"] = {
            "declared": declared,
            "observed": _compact_dict(
                {
                    **_path_metadata(site.model.path),
                    **_infer_hf_metadata(site.model.path),
                }
            ),
            "manifest": _relative_file_manifest(site.model.path),
        }
    else:
        legacy_identity = config.identity.model if config.identity else None
        artifacts["model"] = {
            "declared": _compact_dict(
                {
                    "path": config.model.path,
                    "hf_repo": getattr(legacy_identity, "repo", None),
                    "revision": getattr(legacy_identity, "revision", None),
                    "precision": config.model.precision,
                }
            ),
            "observed": _compact_dict(
                {
                    **_path_metadata(config.model.path),
                    **_infer_hf_metadata(config.model.path),
                }
            ),
            "manifest": _relative_file_manifest(config.model.path),
        }

    if site and site.speculative_model:
        spec = site.speculative_model
        artifacts["speculative_model"] = {
            "declared": _compact_dict(
                {
                    "path": spec.path,
                    "target": spec.target,
                    "hf_repo": spec.hf_repo,
                    "revision": spec.revision,
                }
            ),
            "observed": _compact_dict(
                {
                    **_path_metadata(spec.path),
                    **_infer_hf_metadata(spec.path),
                }
            ),
            "manifest": _relative_file_manifest(spec.path),
        }

    container_declared: dict[str, Any]
    if site and site.container:
        container_declared = _compact_dict(
            {
                "path": site.container.path,
                "image": site.container.image,
                "digest": site.container.digest,
            }
        )
        declared_frameworks = site.container.frameworks
    else:
        legacy_container = config.identity.container if config.identity else None
        container_declared = _compact_dict(
            {
                "path": config.model.container,
                "image": getattr(legacy_container, "image", None),
            }
        )
        declared_frameworks = config.identity.frameworks if config.identity else {}

    artifacts["container"] = {
        "declared": container_declared,
        "observed": _path_metadata(config.model.container, hash_files=False),
    }

    observed_frameworks = _first_worker_frameworks(worker_fingerprints)
    frameworks_by_worker = _frameworks_by_worker(worker_fingerprints)
    if declared_frameworks or observed_frameworks or frameworks_by_worker:
        artifacts["frameworks"] = _compact_dict(
            {
                "declared": declared_frameworks,
                "observed": observed_frameworks,
                "by_worker": frameworks_by_worker,
            }
        )

    mounts: list[dict[str, Any]] = []
    if site and site.mounts:
        mounts.extend(_mount_manifest(mount_spec) for mount_spec in site.mounts)
    if config.extra_mount:
        mounts.extend(_mount_manifest(mount_spec) for mount_spec in config.extra_mount)
    if mounts:
        artifacts["mounts"] = mounts

    output_declared = {}
    if site and site.output.path:
        output_declared["base_path"] = site.output.path
    if resolved_log_dir:
        output_artifact: dict[str, Any] = {"observed": _path_metadata(str(resolved_log_dir))}
        if output_declared:
            output_artifact["declared"] = output_declared
        artifacts["output"] = output_artifact
    elif output_declared:
        artifacts["output"] = {"declared": output_declared}

    artifacts["runtime_code"] = _runtime_code_artifacts(config, output_dir, resolved_log_dir)

    return artifacts


def build_lock_section(
    config: SrtConfig,
    worker_fingerprints: dict[str, Any] | None = None,
    resolved_log_dir: Path | None = None,
    output_dir: Path | None = None,
    recipe_text: str | None = None,
    verification: list[Any] | None = None,
    results: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build the lock: section dict.

    Args:
        config: The resolved SrtConfig.
        worker_fingerprints: Per-worker fingerprints keyed by worker name.
        resolved_log_dir: Actual log directory path (resolved from template).
        output_dir: Run output directory containing config/sbatch/runtime files.
        recipe_text: Exact preserved recipe text above the lock section.
        verification: List of IdentityCheckResult from verify_identity().
        results: Benchmark results from rollup (if available).
    """
    # Build verification summary
    verification_dict = None
    if verification:
        verified = [r for r in verification if r.passed and "not verifiable" not in r.message]
        declared = [r for r in verification if r.passed and "not verifiable" in r.message]
        fails = [r for r in verification if not r.passed]

        def _status(r: Any) -> str:
            if not r.passed:
                return "FAIL"
            return "DECLARED" if "not verifiable" in r.message else "OK"

        parts = []
        if verified:
            parts.append(f"{len(verified)} verified")
        if declared:
            parts.append(f"{len(declared)} declared")
        if fails:
            parts.append(f"{len(fails)} FAILED")

        verification_dict = {
            "result": ", ".join(parts),
            "verified": len(verified),
            "declared": len(declared),
            "failed": len(fails),
            "checks": [{"field": r.field, "status": _status(r), "message": r.message} for r in verification],
        }

    # Record what aliases resolved to
    resolved = {
        "model_path": config.model.path,
        "container_path": config.model.container,
    }
    if config.site and config.site.speculative_model:
        resolved["speculative_model_path"] = config.site.speculative_model.path
        resolved["speculative_model_target"] = config.site.speculative_model.target
    if resolved_log_dir:
        resolved["log_dir"] = str(resolved_log_dir)

    lock: dict[str, Any] = {
        "version": _LOCKFILE_VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "slurm": collect_slurm_context(),
        "resolved": resolved,
    }

    hashes = _hashes_section(config, recipe_text)
    if hashes:
        lock["hashes"] = hashes

    if config.site:
        lock["site"] = _compact_dict({"name": config.site.name})

    artifacts = build_artifacts_section(config, worker_fingerprints, resolved_log_dir, output_dir)
    if artifacts:
        lock["artifacts"] = artifacts

    if verification_dict:
        lock["verification"] = verification_dict
    if worker_fingerprints:
        lock["fingerprints"] = worker_fingerprints
    if results:
        lock["results"] = results

    return lock


def write_lockfile(
    output_dir: Path,
    config: SrtConfig,
    log_dir: Path | None = None,
    verification: list[Any] | None = None,
    results: dict[str, Any] | None = None,
) -> bool:
    """Write reproduce/recipe.lock.yaml with the original recipe and generated lock section.

    Called twice per job:
    1. At job start (log_dir=None) — writes recipe + lock with SLURM context
    2. At job end (log_dir set) — rewrites with fingerprints + verification + results

    Returns True on success, False on any failure. Never raises.
    """
    try:
        # Read the original recipe from the output directory
        recipe_path = output_dir / "config.yaml"
        if recipe_path.exists():
            recipe_text = recipe_path.read_text()
            # Strip any existing lock: section (from re-runs of lockfiles)
            recipe_text = _strip_lock_section(recipe_text)
        else:
            # Fallback: serialize the config (loses comments/formatting)
            from srtctl.core.schema import SrtConfig

            config_dict = SrtConfig.Schema().dump(config)
            config_dict.pop("lock", None)
            recipe_text = yaml.dump(config_dict, default_flow_style=False, sort_keys=False)
        preserved_recipe_text = recipe_text.rstrip()

        # Build the lock section
        fingerprints = collect_worker_fingerprints(fingerprints_dir(output_dir)) if log_dir else None
        lock_data = build_lock_section(
            config,
            fingerprints,
            resolved_log_dir=log_dir,
            output_dir=output_dir,
            recipe_text=preserved_recipe_text,
            verification=verification,
            results=results,
        )

        # Compute integrity hash over the lock content (before adding the hash itself)
        lock_content_yaml = yaml.dump(lock_data, default_flow_style=False, sort_keys=True)
        lock_data["integrity"] = hashlib.sha256(lock_content_yaml.encode()).hexdigest()

        # Append lock section to recipe
        lock_yaml = yaml.dump({"lock": lock_data}, default_flow_style=False, sort_keys=False)
        lockfile_text = preserved_recipe_text + "\n" + _LOCK_COMMENT + lock_yaml

        path = lockfile_path(output_dir)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(lockfile_text)
        logger.info("Wrote lockfile: %s", path)
        return True
    except Exception as e:
        logger.warning("Failed to write lockfile: %s", e)
        return False


def generate_reproduction_report(
    prev_lock: dict[str, Any],
    new_fingerprints: dict[str, Any],
    new_results: dict[str, Any] | None = None,
    new_artifacts: dict[str, Any] | None = None,
) -> tuple[list[str], list[str], list[str]]:
    """Compare a new run's fingerprints against a previous lockfile's data.

    Compares per-worker: each worker in the previous run is matched against
    the same worker key in the new run. Detects added/removed workers and
    per-worker environment differences. When current artifacts are provided,
    also compares cheap manifest evidence so partial/skipped hashes still catch
    model and mount drift.

    Args:
        prev_lock: The lock: section from the previous lockfile.
        new_fingerprints: Per-worker fingerprints from the new run.
        new_results: Benchmark rollup from the new run (optional).
        new_artifacts: Current run's lock.artifacts section (optional).

    Returns:
        Tuple of (summary_lines, report_lines, issues).
        - summary_lines: short output for sweep log
        - report_lines: full report for reproduce/reproduction-report.txt
        - issues: list of problems found
    """
    import re

    from srtctl.core.fingerprint import _parse_pip_packages

    prev_fps = prev_lock.get("fingerprints", {})
    # TODO: prev_results = prev_lock.get("results") — once rollup format is standardized
    if not prev_fps or not new_fingerprints:
        return [], ["No fingerprints available for comparison."], []

    report_lines: list[str] = []
    summary_lines: list[str] = []
    issues: list[str] = []

    def _short(key: str, val: Any) -> str:
        if key == "cuda_version" and isinstance(val, str) and "release" in val:
            m = re.search(r"release ([\d.]+)", val)
            return m.group(1) if m else str(val)
        if key == "nccl_version" and isinstance(val, str) and val.startswith("("):
            return val.strip("()").replace(", ", ".")
        return str(val)

    def _compare(key: str, prev_val: Any, new_val: Any, prefix: str = "") -> str:
        prev_s = _short(key, prev_val) if prev_val else "?"
        new_s = _short(key, new_val) if new_val else "?"
        match = prev_s == new_s
        icon = "OK" if match else "!!"
        label = f"{prefix}{key}" if prefix else key
        line = f"  {icon}  {label}: {prev_s} == {new_s}" if match else f"  {icon}  {label}: {prev_s} != {new_s}"
        if not match:
            issues.append(f"{label}: {prev_s} -> {new_s}")
        return line

    def _manifest_summary(manifest: dict[str, Any] | None) -> dict[str, Any]:
        if not isinstance(manifest, dict):
            return {}
        raw_hash = manifest.get("hash")
        hash_record = cast(dict[str, Any], raw_hash) if isinstance(raw_hash, dict) else {}
        return _compact_dict(
            {
                "kind": manifest.get("kind"),
                "hash_status": hash_record.get("status"),
                "hash_value": hash_record.get("value"),
                "file_count": manifest.get("file_count"),
                "total_files_seen": manifest.get("total_files_seen"),
                "total_bytes": manifest.get("total_bytes"),
                "truncated": hash_record.get("truncated"),
            }
        )

    def _artifact_manifest_map(artifacts: dict[str, Any] | None) -> dict[str, dict[str, Any]]:
        if not isinstance(artifacts, dict):
            return {}
        manifests: dict[str, dict[str, Any]] = {}
        for name in ["model", "speculative_model"]:
            artifact = artifacts.get(name)
            if isinstance(artifact, dict):
                artifact_dict = cast(dict[str, Any], artifact)
                summary = _manifest_summary(artifact_dict.get("manifest"))
                if summary:
                    manifests[name] = summary

        mounts = artifacts.get("mounts")
        if isinstance(mounts, list):
            for idx, mount in enumerate(mounts):
                if not isinstance(mount, dict):
                    continue
                mount_dict = cast(dict[str, Any], mount)
                target = mount_dict.get("target") or f"mount[{idx}]"
                summary = _manifest_summary(mount_dict.get("manifest"))
                if summary:
                    manifests[f"mount:{target}"] = summary
        return manifests

    def _format_manifest_value(value: Any) -> str:
        if value is None:
            return "?"
        value_s = str(value)
        return value_s[:12] if len(value_s) > 24 else value_s

    def _compare_artifacts() -> None:
        prev_artifacts = prev_lock.get("artifacts")
        if not prev_artifacts:
            return

        report_lines.append("")
        report_lines.append("Artifacts:")
        if not new_artifacts:
            report_lines.append("  -- current artifact manifests unavailable")
            return

        prev_manifests = _artifact_manifest_map(prev_artifacts)
        new_manifests = _artifact_manifest_map(new_artifacts)
        all_names = sorted(set(prev_manifests) | set(new_manifests))
        if not all_names:
            report_lines.append("  -- no comparable artifact manifests")
            return

        fields = ["kind", "hash_status", "file_count", "total_files_seen", "total_bytes", "truncated"]
        for name in all_names:
            prev_manifest = prev_manifests.get(name)
            new_manifest = new_manifests.get(name)
            if prev_manifest is None:
                line = f"  !!  artifact {name}: added"
                report_lines.append(line)
                summary_lines.append(line)
                issues.append(f"artifact {name}: added")
                continue
            if new_manifest is None:
                line = f"  !!  artifact {name}: missing"
                report_lines.append(line)
                summary_lines.append(line)
                issues.append(f"artifact {name}: missing")
                continue

            report_lines.append(f"  [{name}]")
            for field in fields:
                prev_val = prev_manifest.get(field)
                new_val = new_manifest.get(field)
                if prev_val is None and new_val is None:
                    continue
                prev_s = _format_manifest_value(prev_val)
                new_s = _format_manifest_value(new_val)
                if prev_val == new_val:
                    report_lines.append(f"    OK  {field}: {prev_s} == {new_s}")
                else:
                    line = f"    !!  {field}: {prev_s} != {new_s}"
                    report_lines.append(line)
                    summary_lines.append(f"  !!  artifact {name} {field}: {prev_s} != {new_s}")
                    issues.append(f"artifact {name} {field}: {prev_s} -> {new_s}")

            prev_hash = prev_manifest.get("hash_value")
            new_hash = new_manifest.get("hash_value")
            if prev_hash and new_hash:
                prev_s = _format_manifest_value(prev_hash)
                new_s = _format_manifest_value(new_hash)
                if prev_hash == new_hash:
                    report_lines.append(f"    OK  manifest_hash: {prev_s} == {new_s}")
                else:
                    line = f"    !!  manifest_hash: {prev_s} != {new_s}"
                    report_lines.append(line)
                    summary_lines.append(f"  !!  artifact {name} manifest_hash: {prev_s} != {new_s}")
                    issues.append(f"artifact {name} manifest_hash: {prev_s} -> {new_s}")

    def _compare_worker(
        worker: str,
        prev_fp: dict[str, Any],
        new_fp: dict[str, Any],
        to_summary: bool = True,
    ) -> None:
        """Compare a single worker pair — appends to report_lines and optionally summary_lines."""
        # Hardware
        prev_gpus = prev_fp.get("gpu", {})
        new_gpus = new_fp.get("gpu", {})
        prev_gpu_name = prev_gpus.get("gpus", [{}])[0].get("name", "?") if prev_gpus.get("gpus") else "?"
        new_gpu_name = new_gpus.get("gpus", [{}])[0].get("name", "?") if new_gpus.get("gpus") else "?"
        prev_gpu_count = len(prev_gpus.get("gpus", []))
        new_gpu_count = len(new_gpus.get("gpus", []))

        report_lines.append("  Hardware:")
        line = _compare("gpu", f"{prev_gpu_count}x {prev_gpu_name}", f"{new_gpu_count}x {new_gpu_name}")
        report_lines.append(f"  {line}")
        if to_summary:
            summary_lines.append(line)
        line = _compare("driver", prev_gpus.get("driver"), new_gpus.get("driver"))
        report_lines.append(f"  {line}")
        if to_summary:
            summary_lines.append(line)

        # Environment
        report_lines.append("  Environment:")
        for key in ["arch", "python_version", "cuda_version", "nccl_version", "os"]:
            line = _compare(key, prev_fp.get(key), new_fp.get(key))
            report_lines.append(f"  {line}")
            if to_summary:
                summary_lines.append(line)

        # Frameworks
        prev_fw = prev_fp.get("frameworks", {})
        new_fw = new_fp.get("frameworks", {})
        if prev_fw or new_fw:
            report_lines.append("  Frameworks:")
            for name in sorted(set(prev_fw) | set(new_fw)):
                line = _compare(name, prev_fw.get(name), new_fw.get(name))
                report_lines.append(f"  {line}")
                if to_summary:
                    summary_lines.append(line)

        # Env vars (report only)
        prev_env = prev_fp.get("env", {})
        new_env = new_fp.get("env", {})
        all_env_keys = sorted(set(prev_env) | set(new_env))
        env_diffs = [
            f"    !!  {k}: {prev_env.get(k)} -> {new_env.get(k)}"
            for k in all_env_keys
            if prev_env.get(k) != new_env.get(k)
        ]
        report_lines.append(f"  Env Vars: {len(all_env_keys)} compared, {len(env_diffs)} differ")
        if env_diffs:
            report_lines.extend(env_diffs)
            issues.append(f"{worker}: env vars differ ({len(env_diffs)})")

        # Pip packages (report only)
        prev_pkgs = _parse_pip_packages(prev_fp.get("pip_packages", {}))
        new_pkgs = _parse_pip_packages(new_fp.get("pip_packages", {}))
        all_pkg_names = sorted(set(prev_pkgs) | set(new_pkgs))
        pkg_changed, pkg_added, pkg_removed, pkg_matched = [], [], [], 0
        for name in all_pkg_names:
            pv, nv = prev_pkgs.get(name), new_pkgs.get(name)
            if pv and nv and pv == nv:
                pkg_matched += 1
            elif pv and nv:
                pkg_changed.append(f"    !!  {name}: {pv} -> {nv}")
            elif pv:
                pkg_removed.append(f"    --  {name}: {pv} (removed)")
            else:
                pkg_added.append(f"    ++  {name}: {nv} (added)")
        report_lines.append(
            f"  Pip: {pkg_matched} match, {len(pkg_changed)} changed, "
            f"{len(pkg_added)} added, {len(pkg_removed)} removed"
        )
        report_lines.extend(pkg_changed)
        report_lines.extend(pkg_added)
        report_lines.extend(pkg_removed)
        if pkg_changed or pkg_added or pkg_removed:
            issues.append(
                f"{worker}: pip packages differ "
                f"({len(pkg_changed)} changed, {len(pkg_added)} added, {len(pkg_removed)} removed)"
            )

    # --- Header ---
    prev_job = prev_lock.get("slurm", {}).get("job_id", "?")
    report_lines.append("=" * 70)
    report_lines.append("Reproduction Report")
    report_lines.append(f"Comparing against lockfile from job {prev_job}")
    report_lines.append("=" * 70)

    # --- Worker topology ---
    prev_workers = sorted(prev_fps.keys())
    new_workers = sorted(new_fingerprints.keys())
    report_lines.append("")
    report_lines.append(f"Workers: previous={prev_workers}, current={new_workers}")
    if prev_workers != new_workers:
        issues.append(f"Worker topology changed: {prev_workers} -> {new_workers}")
        summary_lines.append(f"  !!  workers: {prev_workers} != {new_workers}")

    # --- Per-worker comparison ---
    matched_workers = sorted(set(prev_workers) & set(new_workers))
    only_prev = sorted(set(prev_workers) - set(new_workers))
    only_new = sorted(set(new_workers) - set(prev_workers))

    for worker in matched_workers:
        report_lines.append("")
        report_lines.append(f"[{worker}]")
        # Only add to summary for the first worker (avoid noise for identical workers)
        _compare_worker(worker, prev_fps[worker], new_fingerprints[worker], to_summary=(worker == matched_workers[0]))

    for worker in only_prev:
        report_lines.append("")
        report_lines.append(f"[{worker}] REMOVED (was in previous run)")
        issues.append(f"Worker {worker} removed")

    for worker in only_new:
        report_lines.append("")
        report_lines.append(f"[{worker}] ADDED (not in previous run)")
        issues.append(f"Worker {worker} added")

    _compare_artifacts()

    # --- Results ---
    # TODO: compare benchmark results once rollup format is standardized.

    # --- Summary ---
    report_lines.append("")
    report_lines.append("=" * 70)
    if issues:
        report_lines.append(f"ISSUES FOUND: {len(issues)}")
        for issue in issues:
            report_lines.append(f"  - {issue}")
    else:
        report_lines.append("No issues found. Environment is equivalent to the original run.")
    report_lines.append("=" * 70)

    return summary_lines, report_lines, issues


def _strip_lock_section(yaml_text: str) -> str:
    """Remove the top-level lock: section from YAML text.

    Only matches 'lock:' at column 0 (top-level key) to avoid stripping
    nested fields like 'model: {lock: value}'. Also strips the preceding
    comment banner.
    """
    lines = yaml_text.splitlines(keepends=True)
    result = []
    in_lock = False
    for line in lines:
        # Only match lock: at the START of a line (top-level YAML key)
        if not in_lock and (line.startswith("lock:") or "Lock section — generated by srtctl" in line):
            in_lock = True
            # Strip preceding blank lines and comment banner
            while result and (result[-1].strip() == "" or result[-1].strip().startswith("# ===")):
                result.pop()
            continue
        if in_lock:
            continue
        result.append(line)
    return "".join(result)


def verify_lock_integrity(lock_data: dict[str, Any]) -> bool:
    """Verify that a lock section hasn't been tampered with.

    Recomputes the SHA256 hash over the lock content (excluding the integrity
    field itself) and compares against the stored hash.

    Returns True if the hash matches, False if tampered or no hash present.
    """
    stored_hash = lock_data.get("integrity")
    if not stored_hash:
        return False

    # Recompute hash without the integrity field
    check_data = {k: v for k, v in lock_data.items() if k != "integrity"}
    content_yaml = yaml.dump(check_data, default_flow_style=False, sort_keys=True)
    computed_hash = hashlib.sha256(content_yaml.encode()).hexdigest()

    return computed_hash == stored_hash


def load_lockfile_fingerprints(path: Path) -> dict[str, Any] | None:
    """Load per-worker fingerprints from a lockfile, output directory, or raw JSON."""
    try:
        if path.is_dir():
            lockfile = lockfile_path(path)
            if lockfile.exists():
                return _load_fingerprints_from_lockfile(lockfile)
            raw_dir = fingerprints_dir(path)
            if raw_dir.is_dir():
                return collect_worker_fingerprints(raw_dir)
            return collect_worker_fingerprints(path)

        if path.suffix in (".yaml", ".yml"):
            return _load_fingerprints_from_lockfile(path)

        if path.suffix == ".json":
            fp = load_fingerprint(path)
            if fp is not None:
                worker_key = path.stem.removeprefix("fingerprint_") or "worker"
                return {worker_key: fp}
            return None

        return None
    except Exception as e:
        logger.debug("Failed to load fingerprints from %s: %s", path, e)
        return None


def _load_fingerprints_from_lockfile(path: Path) -> dict[str, Any] | None:
    """Extract per-worker fingerprints from a lockfile YAML."""
    try:
        data = yaml.safe_load(path.read_text())
        if not isinstance(data, dict):
            return None
        # New format: lock.fingerprints
        lock = data.get("lock")
        if isinstance(lock, dict):
            fps = lock.get("fingerprints")
            if isinstance(fps, dict):
                return fps
        # Legacy format: top-level fingerprints
        fps = data.get("fingerprints")
        if isinstance(fps, dict):
            return fps
        fp = data.get("fingerprint")
        if isinstance(fp, dict):
            return {"worker": fp}
        return None
    except Exception as e:
        logger.debug("Failed to parse lockfile %s: %s", path, e)
        return None
