# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Lockfile generation for reproducible benchmark runs.

The lockfile is the original recipe YAML with a `lock:` section appended.
It captures everything needed to understand and reproduce a run:

- The recipe (unchanged, with aliases and identity block)
- lock.slurm: where and how the job ran (job ID, cluster, nodes)
- lock.resolved: what aliases mapped to (local paths)
- lock.verification: identity checks (did runtime match declarations?)
- lock.fingerprints: per-worker runtime environment (GPU, frameworks, packages)
- lock.results: benchmark metrics (throughput, latency)

The lockfile IS a valid recipe — `srtctl apply recipe.lock.yaml` works.
When applying a lockfile, srtctl compares the new run against lock.fingerprints.

All operations are fault-tolerant — lockfile writing never blocks or fails a job.
"""

from __future__ import annotations

import contextlib
import getpass
import hashlib
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

from srtctl.core.fingerprint import load_fingerprint

if TYPE_CHECKING:
    from srtctl.core.schema import SrtConfig

logger = logging.getLogger(__name__)

# Lockfile format version — bump when the structure changes
_LOCKFILE_VERSION = 2

# Comment inserted above the lock section
_LOCK_COMMENT = """\

# ============================================================================
# Lock section — generated by srtctl after a run. DO NOT edit manually.
#
# This records exactly what happened when this recipe was executed.
# To reproduce on another cluster:
#   1. Ensure your srtslurm.yaml has the same model/container aliases
#   2. Run: srtctl apply -f this-file.lock.yaml
#   3. srtctl will compare your runtime against the original fingerprints
#
# The recipe above is unchanged from what the author wrote.
# ============================================================================
"""

# SLURM environment variables to capture.
_SLURM_ENV_KEYS = [
    ("job_id", "SLURM_JOB_ID"),
    ("job_name", "SLURM_JOB_NAME"),
    ("cluster", "SLURM_CLUSTER_NAME"),
    ("account", "SLURM_JOB_ACCOUNT"),
    ("partition", "SLURM_JOB_PARTITION"),
    ("nodelist", "SLURM_JOB_NODELIST"),
    ("num_nodes", "SLURM_JOB_NUM_NODES"),
    ("gpus_per_node", "SLURM_GPUS_PER_NODE"),
    ("time_limit", "SLURM_TIMELIMIT"),
]


def collect_slurm_context() -> dict[str, Any]:
    """Collect SLURM job context from environment variables."""
    ctx: dict[str, Any] = {}

    for key, env_var in _SLURM_ENV_KEYS:
        val = os.environ.get(env_var)
        if val is not None:
            ctx[key] = val

    with contextlib.suppress(Exception):
        ctx["user"] = getpass.getuser()

    ctx["cwd"] = str(Path.cwd())

    srtctl_root = os.environ.get("SRTCTL_ROOT")
    if srtctl_root:
        ctx["srtctl_root"] = srtctl_root

    try:
        import subprocess

        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=2,
            cwd=srtctl_root or None,
        )
        if result.returncode == 0:
            ctx["srtctl_commit"] = result.stdout.strip()
    except Exception:
        pass

    return ctx


def collect_worker_fingerprints(log_dir: Path) -> dict[str, Any] | None:
    """Load per-worker fingerprint files into a dict keyed by worker name."""
    try:
        fp_files = sorted(log_dir.glob("fingerprint_*.json"))
    except Exception as e:
        logger.debug("Failed to glob fingerprint files in %s: %s", log_dir, e)
        return None

    if not fp_files:
        return None

    result: dict[str, Any] = {}
    for fp_file in fp_files:
        fp = load_fingerprint(fp_file)
        if fp is not None:
            worker_key = fp_file.stem.removeprefix("fingerprint_")
            result[worker_key] = fp

    return result if result else None


def build_lock_section(
    config: SrtConfig,
    worker_fingerprints: dict[str, Any] | None = None,
    resolved_log_dir: Path | None = None,
    verification: list[Any] | None = None,
    results: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build the lock: section dict.

    Args:
        config: The resolved SrtConfig.
        worker_fingerprints: Per-worker fingerprints keyed by worker name.
        resolved_log_dir: Actual log directory path (resolved from template).
        verification: List of IdentityCheckResult from verify_identity().
        results: Benchmark results from rollup (if available).
    """
    # Build verification summary
    verification_dict = None
    if verification:
        passes = [r for r in verification if r.passed]
        fails = [r for r in verification if not r.passed]
        verification_dict = {
            "result": "all OK" if not fails else f"{len(fails)} FAILED",
            "passed": len(passes),
            "failed": len(fails),
            "checks": [
                {"field": r.field, "status": "OK" if r.passed else "FAIL", "message": r.message} for r in verification
            ],
        }

    # Record what aliases resolved to
    resolved = {
        "model_path": config.model.path,
        "container_path": config.model.container,
    }
    if resolved_log_dir:
        resolved["log_dir"] = str(resolved_log_dir)

    lock: dict[str, Any] = {
        "version": _LOCKFILE_VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "slurm": collect_slurm_context(),
        "resolved": resolved,
    }

    if verification_dict:
        lock["verification"] = verification_dict
    if worker_fingerprints:
        lock["fingerprints"] = worker_fingerprints
    if results:
        lock["results"] = results

    return lock


def write_lockfile(
    output_dir: Path,
    config: SrtConfig,
    log_dir: Path | None = None,
    verification: list[Any] | None = None,
    results: dict[str, Any] | None = None,
) -> bool:
    """Write recipe.lock.yaml — the original recipe with a lock: section appended.

    Called twice per job:
    1. At job start (log_dir=None) — writes recipe + lock with SLURM context
    2. At job end (log_dir set) — rewrites with fingerprints + verification + results

    Returns True on success, False on any failure. Never raises.
    """
    try:
        # Read the original recipe from the output directory
        recipe_path = output_dir / "config.yaml"
        if recipe_path.exists():
            recipe_text = recipe_path.read_text()
            # Strip any existing lock: section (from re-runs of lockfiles)
            recipe_text = _strip_lock_section(recipe_text)
        else:
            # Fallback: serialize the config (loses comments/formatting)
            from srtctl.core.schema import SrtConfig

            config_dict = SrtConfig.Schema().dump(config)
            config_dict.pop("lock", None)
            recipe_text = yaml.dump(config_dict, default_flow_style=False, sort_keys=False)

        # Build the lock section
        fingerprints = collect_worker_fingerprints(log_dir) if log_dir else None
        lock_data = build_lock_section(
            config,
            fingerprints,
            resolved_log_dir=log_dir,
            verification=verification,
            results=results,
        )

        # Compute integrity hash over the lock content (before adding the hash itself)
        lock_content_yaml = yaml.dump(lock_data, default_flow_style=False, sort_keys=True)
        lock_data["integrity"] = hashlib.sha256(lock_content_yaml.encode()).hexdigest()

        # Append lock section to recipe
        lock_yaml = yaml.dump({"lock": lock_data}, default_flow_style=False, sort_keys=False)
        lockfile_text = recipe_text.rstrip() + "\n" + _LOCK_COMMENT + lock_yaml

        lockfile_path = output_dir / "recipe.lock.yaml"
        lockfile_path.write_text(lockfile_text)
        logger.info("Wrote lockfile: %s", lockfile_path)
        return True
    except Exception as e:
        logger.warning("Failed to write lockfile: %s", e)
        return False


def _strip_lock_section(yaml_text: str) -> str:
    """Remove an existing lock: section from YAML text."""
    lines = yaml_text.splitlines(keepends=True)
    result = []
    in_lock = False
    for line in lines:
        if not in_lock and (line.strip() == "lock:" or "Lock section — generated by srtctl" in line):
            in_lock = True
            while result and (result[-1].strip() == "" or result[-1].strip().startswith("# ===")):
                result.pop()
            continue
        if in_lock:
            continue
        result.append(line)
    return "".join(result)


def verify_lock_integrity(lock_data: dict[str, Any]) -> bool:
    """Verify that a lock section hasn't been tampered with.

    Recomputes the SHA256 hash over the lock content (excluding the integrity
    field itself) and compares against the stored hash.

    Returns True if the hash matches, False if tampered or no hash present.
    """
    stored_hash = lock_data.get("integrity")
    if not stored_hash:
        return False

    # Recompute hash without the integrity field
    check_data = {k: v for k, v in lock_data.items() if k != "integrity"}
    content_yaml = yaml.dump(check_data, default_flow_style=False, sort_keys=True)
    computed_hash = hashlib.sha256(content_yaml.encode()).hexdigest()

    return computed_hash == stored_hash


def load_lockfile_fingerprints(path: Path) -> dict[str, Any] | None:
    """Load per-worker fingerprints from a lockfile, output directory, or raw JSON."""
    try:
        if path.is_dir():
            lockfile = path / "recipe.lock.yaml"
            if lockfile.exists():
                return _load_fingerprints_from_lockfile(lockfile)
            logs_dir = path / "logs"
            if logs_dir.is_dir():
                return collect_worker_fingerprints(logs_dir)
            return collect_worker_fingerprints(path)

        if path.suffix in (".yaml", ".yml"):
            return _load_fingerprints_from_lockfile(path)

        if path.suffix == ".json":
            fp = load_fingerprint(path)
            if fp is not None:
                worker_key = path.stem.removeprefix("fingerprint_") or "worker"
                return {worker_key: fp}
            return None

        return None
    except Exception as e:
        logger.debug("Failed to load fingerprints from %s: %s", path, e)
        return None


def _load_fingerprints_from_lockfile(path: Path) -> dict[str, Any] | None:
    """Extract per-worker fingerprints from a lockfile YAML."""
    try:
        data = yaml.safe_load(path.read_text())
        if not isinstance(data, dict):
            return None
        # New format: lock.fingerprints
        lock = data.get("lock")
        if isinstance(lock, dict):
            fps = lock.get("fingerprints")
            if isinstance(fps, dict):
                return fps
        # Legacy format: top-level fingerprints
        fps = data.get("fingerprints")
        if isinstance(fps, dict):
            return fps
        fp = data.get("fingerprint")
        if isinstance(fp, dict):
            return {"worker": fp}
        return None
    except Exception as e:
        logger.debug("Failed to parse lockfile %s: %s", path, e)
        return None
